version: '3.3'
services:
  starb2w:    
    build:
      dockerfile: ./Dockerfile
      context: .
    environment:
     - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/starB2W
    ports:
     - 8080:8080
    networks: 
     - java-mongo-network
    depends_on:
     - mongodb
    
  mongodb:
    container_name: mongo
    image: mongo
    ports:
     - 27017:27017
    volumes:
        - my-mongo-volume:/data/db
    networks: 
     - java-mongo-network
  
volumes:
  my-mongo-volume:
    
       
networks: 
  java-mongo-network:
    driver: bridge


