version: '3.1'
services:
  starb2w:    
    build: .
    environment:
      ENVIRONMENT: local
      MAX_JAVA_MEMORY: 512
      MIN_JAVA_MEMORY: 256
    ports:
     - "8080:8080"
    links:
    - mongo
    depends_on:
    - mongo

  mongo:
    container_name: mongo
    image: mongo
    expose:
    - 27015
    ports:
    - "27015:27015"
