version: '3.1'
services:

  mongo:
    container_name: mongo
    image: mongo
    expose:
     - 27017
    ports:
     - "27017:27017"
  starb2w:    
    build: .
    environment:
     - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/starB2W

    
    ports:
     - "8080:8080"
    links:
    - mongo
    depends_on:
    - mongo


