server:
  servlet:
    context-path: /starB2W
    
spring:
  data:    mongodb:
      uri: mongodb://localhost:27017/starB2W
  main:    allow-bean-definition-overriding: true
  autoconfigure:
    exclude:    - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration    